#!/bin/bash
TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
SAVELOCATION=/vagrant/backups/backup_$TIMESTAMP

mkdir -p /vagrant/backups/backup_$TIMESTAMP

su -c 'pg_dump moodle' postgres > $SAVELOCATION/moodle.sql

cp -r /var/www/moodledata $SAVELOCATION/

tar -czf $SAVELOCATION.tar.gz $SAVELOCATION

rm -rf $SAVELOCATION